### ISSUE TITLE
CRC error (-f option)

### ISSUE THREAD

**Issue by mizubuch** [koturn/RecompressZip#1]
-f オプションを付けると、まれにファイルが壊れます。

再圧縮してもサイズ圧縮できなかったファイルが、"無圧縮"ではなく"Deflate"属性が付いてしまうために、CRCエラーになります。
バイナリエディタで"Deflate:08h"を"無圧縮:00h"に書き換えるとCRCエラーが出なくなります。
[sample.zip](https://github.com/koturn/RecompressZip/files/9474849/sample.zip)

**Comment by koturn** [comment]
ご連絡ありがとうございます。
[#e320730](https://github.com/koturn/RecompressZip/commit/e32073072868e5802783c63d41609c5971b859b7) にて解決いたしました。
